### ISSUE TITLE
Grid not displaying results TypeError

### ISSUE THREAD

**Issue by clinta** [questdb/ui#127]
After the latest QuestDB update, results are no longer shown in the grid. The query response is valid, and has the data. And the header shows a number of rows returned. But none are displayed. Drawing charts still works. The following error is in the js console.

```
qdb.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'digest')
    at qdb.js:2:913132
    at qdb.js:2:913264
    at qdb.js:2:913268
(anonymous) @ qdb.js:2
(anonymous) @ qdb.js:2
(anonymous) @ qdb.js:2
setTimeout (async)
(anonymous) @ qdb.js:2
setData @ qdb.js:2
(anonymous) @ qdb.js:2
dispatch @ qdb.js:2
m.handle @ qdb.js:2
trigger @ qdb.js:2
(anonymous) @ qdb.js:2
each @ qdb.js:2
each @ qdb.js:2
trigger @ qdb.js:2
(anonymous) @ qdb.js:2
Promise.then (async)
(anonymous) @ qdb.js:2
Dl @ qdb.js:2
t.unstable_runWithPriority @ qdb.js:2
Wi @ qdb.js:2
Ll @ qdb.js:2
(anonymous) @ qdb.js:2
P @ qdb.js:2
E.port1.onmessage @ qdb.js:2
```

![image](https://user-images.githubusercontent.com/3177437/231195326-349001aa-c092-4380-bfd0-57e764f099c1.png)

**Comment by bluestreak01** [comment]
this is fixed
